#! /bin/sh
sxhkd &

bspc monitor HDMI-0 -d I II III IV V
bspc monitor HDMI-2 -d VI VII VIII IX X 

bspc config border_width         6
bspc config window_gap          16
bspc config click_to_focus	true

bspc config normal_border_color "#1d2426"
bspc config active_border_color "#986a46"
bspc config focused_border_color "#986a46"
bspc config presel_feedback_color "#1d2426"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
