#! /bin/sh

sxhkd &

bspc monitor HDMI-0 -d I II III IV V
bspc monitor HDMI-2 -d VI VII VIII IX X 

bspc config border_width         6
bspc config window_gap          16
bspc config click_to_focus	true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
